marionettejs/marionette.inspector

- extension/css/inspector/partials/_header.scss
- extension/js/inspector/app/views/Layout.js
- extension/templates/devTools/appLayout.html
We'll probably want to show if there is a back or forward route available... but that can come down the road. 
Also @nerdpruitt this header needs some serious attention now. it's filling up
> Add back and forward buttons

- extension/templates/devTools/appLayout.html
it's now expected to be on the data-tool node
> data-route broken

- extension/js/agent/components/addCidToComponent.js
- extension/js/agent/utils/getHiddenProperty.js
- extension/js/agent/utils/setHiddenProperty.js
> Set hidden property

- extension/js/agent/patches/patchAppComponentTrigger.js
- extension/js/agent/patches/patchBackboneCollection.js
- extension/js/agent/patches/patchBackboneModel.js
- extension/js/agent/patches/patchBackboneRouter.js
- extension/js/agent/patches/patchBackboneView.js
- extension/js/agent/patches/patchMarionetteApplication.js
+ wrap many patches in iife
+ wrap patchAppComponentTrigger in iife
@paulfalgout - you'll like this one
> [agent] Refactor patches

- extension/js/agent/patches/patchBackboneComponent.js
- extension/js/agent/patches/patchMarionette.js
- extension/js/agent/patches/patchMarionetteApplication.js
- extension/js/inspector/app.js
- extension/js/test/libs/marionette.js
- extension/js/test/unit/AgentSpecRunner.html
- extension/js/test/unit/agent/patches/patchMarionetteApplication.spec.js
So the big problem was that Marionette Application in 2.3 always has an initialize function. Worse, it gets set in Mn.Object so the lookup has to leverage the prototype chain
> Fix Mn 2.3

- extension/js/agent/patches/patchBackboneComponent.js
- extension/js/agent/serializes/serializeChannelRadio.js
This *might* be enough to get es6 classes to work
> Remove extend requirement for patchBackboneComponent

- extension/js/inspector/app/modules/UI/views/ViewTree.js
- extension/templates/devTools/ui/tree.html
https://github.com/marionettejs/marionette.inspector/issues/232
> hide app root in UI tree

- extension/js/inspector/app/modules/Activity.js
- extension/js/inspector/app/modules/Activity/models/ActionCollection.js
- extension/js/inspector/app/modules/Activity/views/Layout.js
https://github.com/marionettejs/marionette.inspector/issues/244
> reset action collapse on render

- README.md
> Add Marionette Wires to README

- README.md
http://www.marionettewires.com is now live
> Update Wires URL

- docs/faq.md
Changed from window.__agent.patchedApplication to from window.__agent.patchedApp
> Fixed app name in FAQ

- extension/js/lib/watchjs/src/watch.js
Fixes regression at
https://github.com/marionettejs/marionette.inspector/commit/8b35f9d5cf1626331243044d01a421095dd94891#diff-e91f5c7f3ab234d724f3d9c20c4835d5L378
> fix: better handle undefined / invalid getters

- .gitignore
- bower.json
- extension/js/inspector/app/modules/Activity.js
- extension/js/inspector/app/modules/Activity/models/ActivityCollection.js
- extension/js/inspector/app/modules/Activity/views/Action.js
- extension/js/inspector/app/modules/Activity/views/ActivityGraph.js
- extension/js/inspector/app/modules/Activity/views/Layout.js
- extension/js/inspector/main.js
- extension/templates/devTools/activity/graph.html
- extension/templates/devTools/activity/graph.js
- extension/templates/devTools/activity/layout.html
View is displayed on 'onClickToggle' of Action View
> create, display, and enable interactivity of ActivityGraph ItemView in D3

- .gitignore
- bower.json
- extension/js/inspector/app/modules/Activity.js
- extension/js/inspector/app/modules/Activity/d3/graph.js
- extension/js/inspector/app/modules/Activity/models/ActionCollection.js
- extension/js/inspector/app/modules/Activity/models/ActivityCollection.js
- extension/js/inspector/app/modules/Activity/views/Action.js
- extension/js/inspector/app/modules/Activity/views/ActivityGraph.js
- extension/js/inspector/app/modules/Activity/views/Layout.js
- extension/js/inspector/main.js
- extension/templates/devTools/activity/graph.html
- extension/templates/devTools/activity/graph.js
- extension/templates/devTools/activity/layout.html
Please note: this PR does not yet include updated tool tips. 
Features to come include:
1. Updated tool tips
2. Labeled X and Y axes
3. Summary view with defined view window (using static input fields)
4. Summary view with dynamic sliders (instead of static input fields)
> Implement dynamic view window for ActivityGraph based on user input

- extension/css/inspector/partials/inspector/_inspector-sidebar.scss
- extension/js/inspector/app/modules/UI/views/EmptyMoreInfo.js
- extension/js/inspector/app/modules/UI/views/Layout.js
- extension/js/inspector/app/modules/UI/views/ViewTree.js
- extension/templates/devTools/ui/emptyMoreInfo.html
> Show message in side panel when a empty region is selected

- extension/js/agent/actions/regionInspector.js
- extension/js/agent/patches/patchMarionette.js
- extension/js/agent/utils/knownTypes.js
Fix loading of Mn v3 applications. V2 compatibility kept
Fix #313 #309
> Support inspecting Mn v3 applications

- extension/js/test/unit/agent/marionette/app-observer.spec.js
> Fix region inspector test

- extension/js/lib/watchjs/src/watch.js
Object.observe is dead and we can assume defineProperty will work
> Remove Object.observe code and checks for defineProperty support

- bower.json
We are using a local copy. Later we can evaluate if is worth sync with upstream
> Remove WatchJS from bower

- extension/js/agent/patches/patchBackboneView.js
> Fix watching view _listeningTo property

- CHANGELOG.md
IMO we are ready for a new release
> Add 0.8 version entry to changelog

- README.md
- docs/developing_locally.md
> Updates github URL

- CHANGELOG.md
- extension/manifest.json
- package.json
> Update version to 0.8.1

- package.json
- yarn.lock
Fixes a build issue in windows
> Update grunt-contrib-clean dependency

- extension/js/lib/watchjs/src/watch.js
This makes use of strict comparison where possible, simplify isFunction and isArray, avoid double var declarations
> Cleanup watchjs

- extension/js/agent/actions/observeChanges.js
- extension/js/agent/patches/patchAppComponentTrigger.js
- extension/js/agent/patches/patchBackboneModel.js
- extension/js/agent/patches/patchBackboneRouter.js
- extension/js/agent/patches/patchMarionetteApplication.js
- extension/js/agent/patches/patchMarionetteBehavior.js
- extension/js/agent/patches/patchMarionetteController.js
- extension/js/agent/patches/patchMarionetteModule.js
- extension/js/agent/patches/patchMarionetteObject.js
- extension/js/agent/utils/findKey.js
- extension/js/inspector/app/modules/UI/util/ComponentReportToRegionTreeMap.js
It uses strict comparison where possible, remove unused or redundant variable, add debug call when Marionette is registered by second time
> General cleanup in agent code

- extension/js/inspector/app/modules/Data/views/ModelInfo.js
This is a regression recently introduced
Fix also typo in instanceProperties var
> Fix reference error in Data ModelInfo.templateContext

- extension/js/agent/patches/util/addCidToComponent.js
In Agent.addCidToComponent check if cid already exists before setting the hidden property
> Check cid before setting hidden cid property

- yarn.lock
Fix running build with Node v8
> Update node-sass sub dependency 

- extension/js/agent/patches/patchMarionette.js
- extension/js/inspector/app.js
- extension/js/inspector/app/modules/Radio/views/ChannelInfo.js
- extension/js/inspector/app/modules/Radio/views/Layout.js
- extension/templates/devTools/radio/info.html
Fixes #335
Depending on the Radio version loaded the Commands section is show (or not) in side pane
> Implement showing / hiding Radio Commands section 

- CHANGELOG.md
- README.md
- extension/js/agent/agent.js
- extension/manifest.json
- package.json
> Update version to 0.9 and changes docs accordingly

- recorder/Gemfile.lock
Github is reporting some vulnerabilities in the dependencies
> Update recorder dependencies

- extension/manifest.json
Remove 'unsafe-eval' from CSP settings
> Remove eval from manifest file
