extension/js/agent/utils/serializeObject.js
Methods defined on a prototype can reference `this`, which starts at the
bottom of the hierarchy and attempts to resolve upwards.  However, the
current method of serialization begins resolution at the current
ancestor.
=> fix(serializeObject): resolve prototype calls

extension/js/agent/build/core.js, extension/js/agent/patches/patchBackbone.js, extension/js/agent/patches/patchBackboneExtend.js, extension/js/agent/serializes/serializeChannelWreqr.js, extension/js/agent/serializes/serializeCollection.js, extension/js/agent/serializes/serializeEvents.js, extension/js/agent/serializes/serializeModel.js, extension/js/agent/serializes/serializeView.js, extension/js/test/unit/AgentSpecRunner.html, extension/js/test/unit/agent/patches/patchBackboneExtend.spec.js, extension/templates/devTools/data/collection-row.html, extension/templates/devTools/data/row.html
This is part of https://github.com/marionettejs/marionette.inspector/issues/160
I've added a classId to the extends as well as the base classes:  Model, Collection, View.  (Should we do router as well?)  It's possible the bases don't need it, but then there will be plenty of instantiated objects with no classId.  This way every instantiation is the same.  Thoughts?
Similarly the example diff on the issue was showing:
`this.__super__.prototype.__marionette_inspector_classId__`
`__super__` is rarely if ever available during the serialization so for now I've left that out.
I've added the `classId` to the list name where the `cid` is currently displayed.  Obviously not the end goal, but it's a start at least for proof of concept.  I've listed the todos below.  I'd appreciate a review now.
I …
=> patchBackboneExtend to add classId to Model, Collection and View

extension/js/agent/utils/inspectValue.js, extension/js/agent/utils/objectPath.js, extension/js/lib/watch.js
ES5 getters that would normally throw a `ReferenceError` due to lack of
initialization now gracefully degrade to `undefined`.
=> fix: better handle undefined / invalid getters

extension/js/inspector/util/clientInspect.js
This was broken because we were using this._ and that reference was undefined.
this._ was another fix for when _ wasn't in the window. not sure why this._ fails...
---
I don't know how i worked with out it. Once it was setup, i could add console.logs all throughout the clientInspect code and it'd immediately update both the script and the file. 
Want to setup?
1. right click in the sidebar to add workspace
2. select inspector/extension/js folder
3. right click in clientInspect.js and select map to file
4. prosper
=> Fixes 271 - Clicking a function in the inspector used to jump to source

extension/js/agent/patches/patchBackboneCollection.js
`serializeCollection` takes up a ton of time relative to everything around it by not delegating to the lazy worker
=> make serialize collection lazy

extension/js/agent/actions/observeChanges.js, extension/js/agent/agent.js, extension/js/agent/build/core.js, extension/js/agent/utils/lazyWorker.js, extension/js/lib/watchjs/src/watch.js, extension/js/test/unit/agent_test_setup.js
This extracts the watch js heartbeat so that runs the watcher loop. In lay man terms, the code that tells watch js to check for changes.
The reason that this code was breaking the tests was that the hearbeat checked to see if __agent was on the page, in the tests it wasn't. I extracted the code for a little bit of dependency sanity.
=> Refactor loop to remove customization from watch.js

extension/css/inspector/main.scss, extension/css/inspector/partials/_layout.scss, extension/css/inspector/partials/_panel-list.scss, extension/css/inspector/partials/inspector/_inspector-panel.scss, extension/css/inspector/partials/mixins/_media-queries.scss
I added a few quick little Sass mixins to handle media queries for this (and some we might want in the future)...nothing fancy for now. Then I made the panels stacked with a border at the bottom of the list at smaller widths. The panels go to the current layout of list to the left at "medium" widths and up.
=> Panels stack at small widths

extension/js/agent/patches/patchBackboneView.js, extension/js/agent/serializes/serializeEvents.js, extension/js/agent/serializes/serializeView.js, extension/js/inspector/app/modules/UI/views/ViewMoreInfo.js
One of the main ways that backbone objects (views, models, etc) react to
changes in the environment is by listening to other objects
`obj.listenTo(foo, 'event', 'callback')`.
Going forward, we'll see these events in the inspector for Backbone
Views. they'll be shown in the events section w/ the other objects cid
as part of the event key
https://www.dropbox.com/s/h4dig87eki68kjo/Screenshot%202015-05-17%2016.57.37.jpg
=> Adds serializeListeningTo

extension/js/inspector/app/modules/Data.js, extension/js/inspector/app/modules/Data/models/ClassCollection.js, extension/js/inspector/app/modules/Data/models/ClassModel.js, extension/js/inspector/app/modules/Data/views/ClassModelList.js, extension/js/inspector/app/modules/Data/views/ClassModelRow.js, extension/js/inspector/app/modules/Data/views/Layout.js, extension/templates/devTools/data/class-model-row.html, extension/templates/devTools/data/row.html
This PR has the initial setup for issue #160.
Note one caveat is that once you're in the model instance collection view, you can't go back to your previous view unless you click "Collections" then back to "Models".
The plan is to update the UI later to be an accordion-type view where you will always see the class model list, and clicking a down arrow will toggle open the model instance collection view. Then, the arrow will turn into an up arrow, and clicking it will collapse the sub-view.
/cc @kford55
=> Show list of model classes #160

extension/js/agent/utils/inspectValue.js
- when a iframe is present in a template, the formatJquery method in inspectValue.js throws an error
- this is because, an iframe contains an embeded document, which doesn't have a tagName
- Thus, checking whether tagName is not blank, fixes the error
=> support-for-templates-having-iframes

extension/js/agent/patches/patchWindow.js
Watch also Marionette.Module property so only when all properties are set, the Mn instance is patched
Fixes #310 #311
=> Watch for Marionette.Module property

extension/js/agent/utils/lazyWorker.js, extension/js/test/unit/agent/utils/lazyWorker.spec.js, extension/js/test/unit/agent_test_setup.js
Following #282, i found that the reason to the test fails at different, random places is due to jobs added to `Agent.lazyWorker` in previous tests being executed after the test finished.
The PR adds an `onDestroy` handler to` LazyWorker` resetting the job queue and calls `destroy` method after each test. `destroy` is used only in tests and is alternatively possible to reset `lazyWorker.queue` directly.
Now, running tests in node only one test fails and always ('LazyWorker slow jobs added calls stop work').
But i found, by uncommenting debug code, that the problem is the first job not being sufficiently slow. In one of my runs, the first job ran 202 microseconds after worker init and the second job 229 microseconds a difference of 27 microseconds, not enough to trigger the `stopWork` …
=> Fix random fails in tests

extension/js/agent/components/util/sendAppComponentReport.js, extension/js/inspector/client/inspectedPage.js
Currently the timestamp of a report message is passed as a property of data
One of the side effects is the UI tree shows a dummy timestamp region
=> Send report message timestamp as a separate property 

extension/js/agent/actions/regionInspector.js, extension/js/inspector/app/components/tree/models/Node.js, extension/js/inspector/app/modules/UI/models/UiData.js, extension/js/inspector/app/modules/UI/views/ViewTree.js
Currently, a UI tree node uses the view.cid property as the idAttribute ('cid'). When the region is empty the 'cid' field is undefined
This has, at least two issues:
- An access violation occurs in https://github.com/marionettejs/marionette.inspector/blob/master/extension/js/inspector/app/components/tree/models/Node.js#L85 when there's no cid / id
- When there at least two empty regions and one of them shows a view, will duplicate entry. This occurs because the previous empty node will be in nodesToUpdate https://github.com/marionettejs/marionette.inspector/blob/master/extension/js/inspector/app/components/tree/models/Node.js#L57 (undefined will be in the currentNodeIds ) and the node with the view will be in nodesToAdd
This PR assign the region cid when the region is empty and set a …
=> Ensure UI tree node always has a id

extension/js/lib/watchjs/src/watch.js
This fix a nasty bug that was making the Agent send messages continuously to the panel. Some background at https://github.com/melanke/Watch.JS/pull/110
=> Add checks in WatchJS to avoid endless loop when watching view._events

extension/js/inspector/app/modules/UI/views/Layout.js, extension/js/inspector/app/modules/UI/views/ViewTree.js
Now that there's a side panel showing the region status and the node has a cid is possible to highlight the empty region when selected.
Improves usability when there are two regions with same name in different levels and the selected is empty
=> Highlight row with empty region

extension/js/background.js, extension/js/inspector/panelPort.js, extension/js/inspector/utils.js
Fixes #218
Replace specific Chrome api
Also jQuery ajax was failing in Firefox. Replaced it by native fetch api
=> Replace Chrome specific API and use fetch instead of $.ajax (fix compatibility with Firefox)

extension/js/agent/utils/lazyWorker.js
Part of #352 
Decrease the defertime to 160. Given that the recent changes reduces the number of actions to execute should have no significant impact.
Also more computation can be in 160ms today than 200ms two years ago
=> Decrease the defertime of lazyworker by 20%

extension/js/agent/patches/patchWindow.js
Fixes loading the inspector when Marionette 3 is used through script tag
=> Rework how Marionette is detected when using script tag

extension/css/inspector/partials/inspector/_inspector-sidebar.scss
The sidebar list item text is being clobbered by below item. This PR fixes it
It also uses the unprefixed user-select rule
=> Update property-tree li style to avoid text clobbering

extension/js/agent/patches/patchMarionette.js, extension/js/agent/serializes/serializeView.js, extension/js/agent/utils/inspectValue.js, extension/js/agent/utils/knownTypes.js, extension/js/agent/utils/objectPath.js, extension/js/test/unit/agent_test_setup.js
Part of #352 
objectPath is the main bottleneck when serializing view or events. It's called very often. There are two factors that make it slow: the call to _.rest and String.split. This PR avoids calling _.rest by passing the path array alongside the index in nested calls. The split still there to, maybe, be handled  later
knownType is also called a lot. This PR make its initialization explicit instead of by demand and reduce the number of calls to it.
=> Optimize knownType and objectPath

extension/js/agent/patches/patchBackboneView.js
Part of #352 
Currently when a view is created is serialized from 2 to 4 times according to what events are configured.
This PR makes the view be serialized only once when created. Also fixes a bug where, after more than one view is changed, only the last one would be updated
=> Reduce the number of times a view is serialized

extension/js/inspector/client/inspectedPage.js
It get the possible values as defined in https://developer.chrome.com/extensions/devtools_inspectedWindow#method-eval
Also show default message when message is falsy
=> Improve error handling in inspectedPage.execFunction

extension/js/agent/utils/sendMessage.js
Respect immediate option that is passed to `Agent.sendMessage`.
The most visible effect is the reduce in latency between changes in region tree and the visualization in UI tab.
With this change #352 can be closed
=> Implement QueuePostMessages sendBatchImmediate

.travis.yml, Gruntfile.js, bower.json, extension/js/test/unit/AgentSpecRunner.html, extension/js/test/unit/agent_test_setup.js, package.json, scripts/test.js, yarn.lock
grunt-mocha is using phantomjs which is not actively maintained. This prevents using newer js features.
This PR implements running mocha tests through puppeteer (Chrome headless node interface)
=> Replace grunt-mocha by running mocha through puppeteer

extension/js/agent/build/core.js, extension/js/agent/utils/lazyWorker.js, extension/js/test/unit/agent_test_setup.js
BackboneEvents  is used only in tests.
Move the LazyWork prototype patch to test setup and remove from agent build
=> Remove BackboneEvents from agent build

extension/js/agent/patches/patchAppComponentTrigger.js
The arguments were not being serialized correctly because the arguments passed by _.map does not match the expected by `inspectValue`
=> Fix serialization of trigger arguments
